-- Historical compatibility marker.
-- This migration was recorded in production before the employee roster base
-- migration. Fresh installs receive the actual employee authorization patch
-- from the post-roster migration 20260930160000.
