import 'package:flutter/material.dart';

class AppColors {
  AppColors._();
  static const primary=Color(0xFF3B82F6); static const brand=primary; static const brandDark=Color(0xFF2563EB); static const brandLight=Color(0xFFEFF6FF); static const accent=primary; static const accentLight=brandLight; static const clay=Color(0xFF92400E); static const clayLight=Color(0xFFFFF7ED); static const ochre=Color(0xFF92400E); static const success=Color(0xFF15803D); static const successLight=Color(0xFFF0FDF4); static const warning=Color(0xFF92400E); static const warningLight=Color(0xFFFFFBEB); static const error=Color(0xFFB91C1C); static const errorLight=Color(0xFFFEF2F2); static const info=primary; static const infoLight=brandLight; static const textPrimaryLight=Color(0xFF111111); static const textSecondaryLight=Color(0xFF4B4B4B); static const mutedLight=Color(0xFF6B6B6B); static const borderLight=Color(0xFFE5E7EB); static const backgroundLight=Color(0xFFFFFFFF); static const surfaceLight=Color(0xFFFFFFFF); static const surfaceAltLight=Color(0xFFF7F8FA); static const backgroundDark=Color(0xFF000000); static const surfaceDark=Color(0xFF111111); static const surfaceAltDark=Color(0xFF1A1A1A); static const borderDark=Color(0xFF303030); static const darkWarning=Color(0xFFFBBF24); static const darkWarningOn=Color(0xFF111111); static const darkError=Color(0xFFF87171); static const darkErrorOn=Color(0xFF111111); static const darkPrimary=Color(0xFF60A5FA); static const darkPrimaryStrong=Color(0xFF93C5FD); static const darkOnPrimary=Color(0xFF000000); static const darkInfo=Color(0xFF60A5FA); static const darkSuccess=Color(0xFF4ADE80); static const darkSuccessOn=Color(0xFF111111); static const darkTextPrimary=Color(0xFFFFFFFF); static const darkTextSecondary=Color(0xFFD1D5DB); static const darkMuted=Color(0xFF9CA3AF);
  static const neutral0=Color(0xFFFFFFFF); static const primary50=Color(0xFFEFF6FF);
  static bool isDark(BuildContext context)=>Theme.of(context).brightness==Brightness.dark;
  static Color primaryOf(BuildContext context)=>isDark(context)?darkPrimary:primary; static Color onPrimaryOf(BuildContext context)=>isDark(context)?darkOnPrimary:neutral0; static Color accentOf(BuildContext context)=>primaryOf(context); static Color successOf(BuildContext context)=>isDark(context)?darkSuccess:success; static Color successOnOf(BuildContext context)=>isDark(context)?darkSuccessOn:neutral0; static Color warningOf(BuildContext context)=>isDark(context)?darkWarning:warning; static Color warningOnOf(BuildContext context)=>isDark(context)?darkWarningOn:neutral0; static Color errorOf(BuildContext context)=>isDark(context)?darkError:error; static Color errorOnOf(BuildContext context)=>isDark(context)?darkErrorOn:neutral0; static Color infoOf(BuildContext context)=>isDark(context)?darkInfo:info; static Color backgroundOf(BuildContext context)=>isDark(context)?backgroundDark:backgroundLight; static Color surfaceOf(BuildContext context)=>isDark(context)?surfaceDark:surfaceLight; static Color surfaceAltOf(BuildContext context)=>isDark(context)?surfaceAltDark:surfaceAltLight; static Color borderOf(BuildContext context)=>isDark(context)?borderDark:borderLight; static Color dividerOf(BuildContext context)=>borderOf(context); static Color textPrimaryOf(BuildContext context)=>isDark(context)?darkTextPrimary:textPrimaryLight; static Color textSecondaryOf(BuildContext context)=>isDark(context)?darkTextSecondary:textSecondaryLight; static Color mutedOf(BuildContext context)=>isDark(context)?darkMuted:mutedLight; static Color selectedTintOf(BuildContext context)=>isDark(context)?darkPrimary.withValues(alpha:AppOpacity.badgeTintDark):primary50;
}
class AppTypography { AppTypography._(); static const display=TextStyle(fontSize:36,fontWeight:FontWeight.w800,height:1.08,letterSpacing:-1); static const title=TextStyle(fontSize:28,fontWeight:FontWeight.w800,height:1.12,letterSpacing:-.6); static const heading=TextStyle(fontSize:22,fontWeight:FontWeight.w700,height:1.18,letterSpacing:-.3); static const subheading=TextStyle(fontSize:18,fontWeight:FontWeight.w600,height:1.3,letterSpacing:-.1); static const bodyLarge=TextStyle(fontSize:18,height:1.5); static const body=TextStyle(fontSize:16,height:1.5); static const caption=TextStyle(fontSize:14,height:1.45); static const label=TextStyle(fontSize:13,fontWeight:FontWeight.w600,height:1.3,letterSpacing:.2); static const buttonLabel=TextStyle(fontSize:16,fontWeight:FontWeight.w700,height:1.2,letterSpacing:.1); static const mono=TextStyle(fontFamily:'Space Mono',fontFamilyFallback:['monospace'],fontSize:16,height:1.25,fontFeatures:[FontFeature.tabularFigures()]); }
class AppSpacing { AppSpacing._(); static const xs=4.0,sm=8.0,md=12.0,lg=16.0,xl=24.0,xxl=32.0,xxxl=48.0; }
class AppRadius { AppRadius._(); static const sm=10.0,md=14.0,lg=18.0,xl=24.0,pill=999.0; }
class AppTouchTarget { AppTouchTarget._(); static const minimum=48.0; }
class AppOpacity { AppOpacity._(); static const badgeTintDark=.18; }
class AppMotion { AppMotion._(); static const fast=Duration(milliseconds:160); }
class AppElevation { AppElevation._(); static List<BoxShadow> cardOf(BuildContext context)=>[BoxShadow(color:Colors.black.withValues(alpha:isDark(context)?.22:.06),blurRadius:20,offset:const Offset(0,8))]; static List<BoxShadow> liftOf(BuildContext context)=>[BoxShadow(color:Colors.black.withValues(alpha:isDark(context)?.28:.08),blurRadius:24,offset:const Offset(0,-4))]; }
