import 'package:flutter/material.dart';

import '../../core/theme/design_tokens.dart';

class FulusPinKeypad extends StatelessWidget {
  const FulusPinKeypad({super.key,required this.onDigit,required this.onBackspace,this.enabled=true});
  final ValueChanged<String> onDigit; final VoidCallback onBackspace; final bool enabled;
  @override Widget build(BuildContext context){const keys=<String>['1','2','3','4','5','6','7','8','9','','0','back'];return LayoutBuilder(builder:(context,constraints){final width=constraints.maxWidth;final keySize=((width-AppSpacing.lg*2)/3).clamp(68.0,92.0);return SizedBox(width:keySize*3+AppSpacing.lg*2,child:GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:keys.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,mainAxisExtent:keySize,crossAxisSpacing:AppSpacing.lg,mainAxisSpacing:AppSpacing.md),itemBuilder:(context,index){final key=keys[index];if(key.isEmpty)return const SizedBox.shrink();final back=key=='back';return _PinKey(label:back?null:key,icon:back?Icons.backspace_rounded:null,enabled:enabled,onTap:back?onBackspace:()=>onDigit(key));}));});}
}
class _PinKey extends StatelessWidget{const _PinKey({required this.label,required this.icon,required this.enabled,required this.onTap});final String? label;final IconData? icon;final bool enabled;final VoidCallback onTap;@override Widget build(BuildContext context){final text=AppColors.textPrimaryOf(context);final secondary=AppColors.textSecondaryOf(context);final border=AppColors.borderOf(context);final surface=AppColors.surfaceOf(context);final back=label==null;return Semantics(button:true,label:back?'Delete last digit':'Digit $label',child:Material(color:Colors.transparent,shape:const CircleBorder(),child:InkWell(onTap:enabled?onTap:null,customBorder:const CircleBorder(),child:Ink(decoration:BoxDecoration(shape:BoxShape.circle,color:back?surface.withValues(alpha:.72):surface,border:Border.all(color:border.withValues(alpha:.55)),boxShadow:[BoxShadow(color:Colors.black.withValues(alpha:.055),blurRadius:16,offset:const Offset(0,6))]),child:Center(child:label!=null?Text(label!,style:TextStyle(fontSize:23,height:1,fontWeight:FontWeight.w600,color:enabled?text:secondary)):Icon(icon,size:20,color:enabled?text:secondary))))));}}
